### ISSUE TITLE
Some Mangas can't be decoded due to a decodingError

### ISSUE THREAD

**Issue by K1NXZ** [JRomainG/MangaDexLib#3]
Error:

```
Swift.DecodingError.typeMismatch(Swift.Dictionary<Swift.String, Swift.String>, Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "results", intValue: nil), _JSONKey(stringValue: "Index 12", intValue: 12), CodingKeys(stringValue: "data", intValue: nil), CodingKeys(stringValue: "attributes", intValue: nil), CodingKeys(stringValue: "links", intValue: nil)], debugDescription: "Expected to decode Dictionary<String, String> but found an array instead.", underlyingError: nil))
```

seems like the MangaDex API is providing an empty array as default value if the "links" property on a manga is empty, but the decoder is expecting a type of:
```swift
Dictionary<String, String>
```

example manga: https://api.mangadex.org/manga/3c483931-7bd2-4fce-8e82-95c6b79ee1f0

**Comment by JRomainG** [comment]
This seems to be the same issue as for the `MDTag.description` attribute where the API returns an empty array instead of an empty dictionary (or `null`) when the attribute is missing

A temporary fix would be to change `MDManga.init(from decoder: Decoder)` with something like this:

```swift
var rawLinks: [String: String] = [:]
do {
    rawLinks = try container.decode([String: String]?.self, forKey: .links) ?? [:]
} catch is DecodingError {
    rawLinks = [:]
}
```

I would rather ask the MangaDex devs first if this is an issue on their side or if it's the intended behavior

**Edit:** It seems the devs have been aware of it for a long time but are not considering fixing it any time soon, because the backend uses PHP for which arrays and dicts are the same object. This means that potentially any dict in the API can be returned as an array instead, which may break pretty much anything...

**Comment by JRomainG** [comment]
Added a workaround for `MDManga.description`, `MDManga.links`, and `MDTag.description` in the commit referenced above
